# typos configuration
# https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
  # Ignore hex strings and hashes
  "[a-fA-F0-9]{32,}",
]

[files]
extend-exclude = ["*.lock", "*.snap", ".sqlx/", "web/src/wasm/", "web/src/api/generated/"]

# Known false positives can be added here:
# [default.extend-words]
# ot = "ot"
